// utils/practitionersData.js

const practitionersData = [{
        title: "General Practitioner",
        remainingVisits: 1,
        name: "John Jacob Smith",
        phone: "0987654321",
        graduationYear: "2012",
        university: "Medical School Name",
        state: "Illinois",
        city: "Chicago",
        country: "USA",
        email: "example@email.com",
        imageUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&w=350&dpr=2",
        primaryClinicName: "Sample Text",
        address: "Akshya Nagar 1st Block 1st Cross , Rammurthy Nagar, Bangalore-560016",
        consulationDays: "Mon - Fri",
        consulationHours: "8am - 2pm",
    },
    {
        title: "Specialist Care Provider",
        remainingVisits: 1,
        name: "John Jacob Smith",
        phone: "0987654321",
        graduationYear: "2012",
        university: "Medical School Name",
        state: "Illinois",
        city: "Chicago",
        email: "example@email.com",

        country: "USA",

        imageUrl: "https://www.thewmch.com/wp-content/uploads/2023/02/female-doctor-using-her-digital-tablet-free-vector.jpg",
    },
    {
        title: "Diagnostic Laboratory Service",
        remainingVisits: 1,
        university: "Medical School Name",
        name: "Sample Title",
        phone: "0987654321",
        email: "example@email.com",
        graduationYear: "2012",
        city: "Chicago",
        country: "USA",

        imageUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&w=350&dpr=2",
    },
    {
        title: "Diagnostic Laboratory Service",
        remainingVisits: 1,
        name: "Sample Title",
        email: "example@email.com",
        university: "Medical School Name",
        graduationYear: "2012",

        phone: "0987654321",
        city: "Chicago",
        country: "USA",

        imageUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&w=350&dpr=2",
    },
    {
        title: "General Practitioner",
        remainingVisits: 1,
        name: "John Jacob Smith",
        email: "example@email.com",
        graduationYear: "2012",

        university: "Medical School Name",
        phone: "0987654321",
        city: "Chicago",
        country: "USA",
        imageUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&w=350&dpr=2",
    },
    {
        title: "General Practitioner",
        remainingVisits: 1,
        name: "John Jacob Smith",
        email: "example@email.com",
        graduationYear: "2012",
        university: "Medical School Name",
        phone: "0987654321",
        city: "Chicago",
        country: "USA",
        imageUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&w=350&dpr=2",
    },
    {
        title: "General Practitioner",
        remainingVisits: 1,
        name: "John Jacob Smith",
        graduationYear: "2012",
        phone: "0987654321",
        university: "Medical School Name",
        email: "example@email.com",
        city: "Chicago",
        country: "USA",
        imageUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&w=350&dpr=2",
    },
];

export default practitionersData;